apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise-gateway
    component: enterprise-gateway
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: enterprise-gateway
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    {{- range $key, $val := .Values.service.ports }}
    -
      {{- range $pkey, $pval := $val }}
      {{ $pkey}}: {{ $pval }}
      {{- end }}
    {{- end }}
  selector:
    gateway-selector: enterprise-gateway
  sessionAffinity: ClientIP
  type: {{ .Values.service.type }}
{{- if .Values.service.externalIPs.k8sMasterPublicIP }}
  externalIPs:
  - {{ .Values.sertvice.externalIPs.k8sMasterPublicIP }}
{{- end }}
